image: rustlang/rust:nightly

test:cargo:
  script:
    - rustc --version
    - cargo --version
    - cargo fmt --check --verbose
    - cargo clippy -- -Dwarnings
    - cargo test --workspace --verbose
    - cd crates/larvae_macros
    - cargo test --workspace --verbose
    - cd ../larvae_core
    - cargo test --workspace --verbose
