[package]
name = "larvae"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
nom = "7.1.0"
pom = "3.2.0"
meval = "0.2.0"
earlgrey = "0.3.0"
lexers = "0.1.3"
shunting = "0.0.9"
rustyline = "5.0.0"
