[package]
name = "larvae"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = {version = "0.31.1", features = ["use_serde"]}
